"""Pydantic data schemas for Stickman Video Director Pipeline."""

from typing import List, Literal, Optional
from pydantic import BaseModel, Field


class ReviewVerdict(BaseModel):
    """Evaluation verdict produced by the Reviewer Agent (DirectorCritic)."""

    is_approved: bool = Field(
        ...,
        description="Whether the Phase A proposal meets all quality standards and is approved for Phase B compilation."
    )
    score: int = Field(
        ...,
        ge=1,
        le=10,
        description="Overall quality score from 1 to 10. Minimum 8 required for approval."
    )
    critique: str = Field(
        ...,
        description="Detailed feedback analyzing physical metaphors, pacing (20-25 words/10s), 5-stage structure, and visual dynamics."
    )
    missing_elements: List[str] = Field(
        default_factory=list,
        description="List of missing, vague, or defective elements that need revision."
    )


class ClipPrompt(BaseModel):
    """Production prompt specification for an individual 10-second clip."""

    index: int = Field(
        ...,
        description="1-based index of the clip (e.g. 1, 2, 3...)."
    )
    duration_sec: int = Field(
        default=10,
        description="Duration of the clip in seconds (standard 10s)."
    )
    prompt: str = Field(
        ...,
        description="Complete, self-contained Omni Flash generation prompt following prompt contract."
    )
    spoken_words: str = Field(
        ...,
        description="The exact audio-only voiceover dialogue spoken during this clip."
    )
    visual_metaphor: str = Field(
        ...,
        description="The tangible physical action or metaphor depicted in the clip."
    )


class PhaseBOutput(BaseModel):
    """Complete Phase B output package ready for video generation in Flow."""

    topic: str = Field(..., description="The main topic of the video.")
    aspect_ratio: str = Field(..., description="Chosen aspect ratio: '9:16' or '16:9'.")
    style: str = Field(..., description="Selected visual style (e.g. Style 1A, Style 2A).")
    total_duration_sec: int = Field(..., description="Total video duration in seconds.")
    clips: List[ClipPrompt] = Field(
        ...,
        description="Ordered list of 10-second clip prompts comprising the entire video."
    )
    stitching_guide: Optional[str] = Field(
        default=None,
        description="Instructions for assembling and match-cutting the generated clips."
    )
    voice_and_music_note: Optional[str] = Field(
        default=None,
        description="Voice actor and background music continuity notes."
    )
    post_production_overlays: List[str] = Field(
        default_factory=list,
        description="Optional text overlays for post-production (not included in raw video generation)."
    )


class TopicIdea(BaseModel):
    """Structured topic proposal generated by the TopicStrategist agent."""

    niche: Literal["niche_1_mindset", "niche_2_social"] = Field(
        ...,
        description="Selected high-level niche: 'niche_1_mindset' (70%) or 'niche_2_social' (30%)."
    )
    sub_category: str = Field(
        ...,
        description="Specific sub-theme from the taxonomy (e.g. 'Friction Theory', 'Boundary Defense')."
    )
    title: str = Field(
        ...,
        description="Punchy, curiosity-inducing hook title optimized for short-form video retention."
    )
    hook_premise: str = Field(
        ...,
        description="The opening contradiction, paradox, or counter-intuitive premise."
    )
    physical_metaphor: str = Field(
        ...,
        description="An inanimate, tangible physical object or mechanism (e.g. leaky cup, treadmill, anchor, locked chest)."
    )
    narrative_angle: str = Field(
        ...,
        description="Brief summary of the visual progression across the narrative."
    )


class TopicHistoryEntry(BaseModel):
    """Persistent log entry for a scheduled or executed video topic."""

    date: str = Field(
        ...,
        description="ISO 8601 timestamp of when the topic was generated and recorded."
    )
    niche: str = Field(
        ...,
        description="Niche classification ('niche_1_mindset' or 'niche_2_social')."
    )
    sub_category: str = Field(
        ...,
        description="Sub-category taxonomy tag."
    )
    title: str = Field(
        ...,
        description="Title of the topic."
    )
    physical_metaphor: str = Field(
        ...,
        description="Primary physical metaphor used in the video."
    )
    folder_path: Optional[str] = Field(
        default=None,
        description="Path to the dedicated topic folder in data/."
    )
